# Generated by Django 2.2.7 on 2020-08-15 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moderator', '0002_course_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multiple_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(blank=True, max_length=500, null=True)),
                ('option2', models.CharField(blank=True, max_length=500, null=True)),
                ('option3', models.CharField(blank=True, max_length=500, null=True)),
                ('option4', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=5, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Code')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Description')),
                ('multipl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Multiple_Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='True_False',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statements', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moderator.Course')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='truefalse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.True_False'),
        ),
        migrations.AddField(
            model_name='multiple_choice',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Title'),
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Title'),
        ),
        migrations.AddField(
            model_name='code',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Title'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Moderator.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
