# Generated by Django 2.2.7 on 2020-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20200815_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code',
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.ManyToManyField(to='Teacher.Code'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.ManyToManyField(to='Teacher.Description'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='multipl',
        ),
        migrations.AddField(
            model_name='question',
            name='multipl',
            field=models.ManyToManyField(to='Teacher.Multiple_Choice'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='truefalse',
        ),
        migrations.AddField(
            model_name='question',
            name='truefalse',
            field=models.ManyToManyField(to='Teacher.True_False'),
        ),
    ]
